/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./blocks/**/*.{html,js,css}","./webpack/**/*.{js,html,ejs}",],
  important: ".tw",
  prefix: "tw-",
  theme: {
    extend: {
      colors: require("./tailwind.colors.js"),
      listStyleType: {
        none: "none",
        disc: "disc",
        decimal: "decimal",
        square: "square",
        roman: "upper-roman",
      },
      fontSize: {
        "xl-display": ["140px", "1"],
        "l-display": ["80px", "1.2"],
        alfa: ["64px", "1.2"],
        bravo: ["52px", "1.2"],
        charlie: ["40px", "1.3"],
        delta: ["32px", "1.3"],
        echo: ["24px", "1.3"],
        xl: ["20px", "30px"],
        lg: ["18px", "26px"],
        base: ["16px", "24px"],
        sm: ["14px", "20px"],
        captionLg: ["14px", "16px"],
        captionSm: ["12px", "14px"],
        mobXlDisplay: ["64px", "72px"],
        mobLDisplay: ["48px", "56px"],
        mobAlfa: ["34px", "42px"],
        mobBravo: ["31px", "38px"],
        mobCharlie: ["27px", "34px"],
        mobDelta: ["23px", "30px"],
        mobEcho: ["20px", "26px"],
        mobXl: ["23px", "30px"],
        mobLg: ["17px", "25px"],
        mobBase: ["15px", "23px"],
        mobSm: ["13px", "18px"],
        mobCaptionLg: ["13px", "16px"],
        mobCaptionSm: ["11px", "14px"],
      },
      fontWeight: {
        thin: "270",
        light: "330",
        normal: "330",
        medium: "370",
        semibold: "400",
        bold: "450",
        bolder: "530",
        extrabold: "800",
        "extra-bold": "800",
        black: "900",
      },
      screens: {
        "max-container": "1536px",
        xxl: "1440px",
      },
      aspectRatio: {
        "2/3": "2 / 3",
        "3/4": "3 / 4",
        "4/3": "4 / 3",
        "4/5": "4 / 5",
        "3/2": "3 / 2",
        "8/5": "8 / 5",
        "16/9": "16 / 9",
      },
      spacing: {
        unset: "unset",
        0: "0",
        px: "0.1rem",
        1: "1px",
        2: "2px",
        4: "4px",
        6: "6px",
        8: "8px",
        9: "9px",
        10: "10px",
        12: "12px",
        14: "14px",
        15: "15px",
        16: "16px",
        18: "18px",
        19: "19px",
        20: "20px",
        22: '22px',
        24: "24px",
        28: "28px",
        30: "30px",
        32: "32px",
        36: "36px",
        40: "40px",
        42: "42px",
        48: "48px",
        54: "54px",
        56: "56px",
        64: "64px",
        72: "72px",
        80: "80px",
        96: "96px",
        100: "100px",
        140: "140px",
        160: "160px",
        128: "128px",
        327: "327px",
        416: "416px",
        500: "500px",
        810: "810px",

        // desktop
        "1/12": "8.333%",
        "2/12": "16.667%",
        "3/12": "25%",
        "4/12": "33.333%",
        "5/12": "41.667%",
        "6/12": "50%",
        "7/12": "58.333%",
        "8/12": "66.667%",
        "9/12": "75%",
        "10/12": "83.333%",
        "11/12": "91.667%",

        // tablet
        "1/8": "12.5%",
        "2/8": "25%",
        "3/8": "37.5%",
        "4/8": "50%",
        "5/8": "62.5%",
        "6/8": "75%",
        "7/8": "87.5%",

        // mobile
        "1/4": "25%",
        "2/4": "50%",
        "3/4": "75%",

        full: "100%",
      },
      width: {
        "16p": "16px",
      },
      height: {
        "16p": "16px",
      },
      maxWidth: {
        "384": "384px",
        "512": "512px",
        "640": "640px",
        "720": "720px",
        "768": "768px"
      },
      letterSpacing: {
        nav: "0.005em",
        tight: "-.01em",
        wide: ".005em",
        wider: ".1em",
        widest: ".3em",
        xlDisplay: "-1.4px",
        lDisplay: "-0.8px",
        lg: "0.048px",
        base: "0.08px",
        sm: "0.07px",
        captionLg: "1.4px",
        captionSm: "1.2px",
        mobLg: "0.085px",
        mobBase: "0.075px",
        mobSm: "0.065px",
        mobCaptionLg: "1.3px",
        mobCaptionSm: "1.1px",
      },
      gridTemplateColumns: {
        productRowLg: "1fr auto 1fr auto 1fr auto 1fr;",
        productRowMd: "1fr auto 1fr;",
      },
      boxShadow: {
        boxShadow: "0px 8px 16px 0px rgba(19, 19, 19, 0.05)"
      }
    },
    fontFamily: {
      sans: ["Geogrotesque"],
    },
    container: {
      center: true,
      padding: {
        DEFAULT: "24px",
        lg: "40px",
        xl: "64px",
      },
    },
  },
  plugins: [
    fluid({
      suffix: "",
      textSizes: {
        "xl-display": {
          min: "64px",
          max: "140px",
          minvw: "600px",
          maxvw: "1280px",
        },
        "l-display": {
          min: "48px",
          max: "80px",
          minvw: "600px",
          maxvw: "1280px",
        },
        alfa: {
          min: "34px",
          max: "64px",
          minvw: "600px",
          maxvw: "1280px",
        },
        bravo: {
          min: "31px",
          max: "52px",
          minvw: "600px",
          maxvw: "1280px",
        },
        charlie: {
          min: "27px",
          max: "40px",
          minvw: "600px",
          maxvw: "1280px",
        },
        delta: {
          min: "23px",
          max: "32px",
          minvw: "600px",
          maxvw: "1280px",
        },
        echo: {
          min: "19px",
          max: "24px",
          minvw: "600px",
          maxvw: "1280px",
        },
        base: {
          min: "15px",
          max: "16px",
          minvw: "600px",
          maxvw: "1280px",
        },
        xl: "20px",
        lg: "18px",
        mobLg: "17px",
        mobBase: "15px",
        sm: "14px",
        mobSm: "13px",
        xs: "12px",
        caption: "13px",
        captionLarge: "14px",
        captionSmall: "12px",
      },
    }),
  ],
  purge: {
    options: {
      safelist: [
        'wallsio-load-more-button', 
        'atomic-container-left-1-col .atomic-richtext-content',
        'document-sub-nav .atomic-container-left-1-col .atomic-richtext-content .atomic-richtext-content-w-full',
        'document-sub-nav .atomic-container-center-1-col .atomic-richtext-content .atomic-richtext-content-w-full',
        'document-sub-nav .atomic-container-left-1-col .media-image .atomic-richtext-content',
        'tw-h-[calc(95svh-64px)]', 'md:tw-h-[calc(95svh-133px)]', 
        'tw-grid-cols-1', 
        'sm:tw-grid-cols-2', 
        'lg:tw-grid-cols-3', 
        'lg:tw-grid-cols-4', 
        '.accordion-content div[role="region"] div section:first-child', 
        '.tab-content div[role="tabpanel"] > div > section', 
        '.tab-content div[role="tabpanel"] .cmp-container div:last-child section:last-of-type', 
        '.cmp-container:has(> .product-row-xf)',
        '.product-row-xf',
        'input[type="range"]',
        'input[type="range" i]::-webkit-slider-thumb',
        'input[type="range"]::-moz-range-thumb',
        'tw-mt-32',
        'tw-mt-16',
        'tw-mt-24',
        'tw-mt-64',
        'md:tw-mt-48',
        'md:tw-mt-24',
        'md:tw-mt-32',
        'md:tw-mt-96',
        'tw-mb-32',
        'tw-mb-16',
        'tw-mb-24',
        'tw-mb-64',
        'md:tw-mb-48',
        'md:tw-mb-24',
        'md:tw-mb-32',
        'md:tw-mb-96',
        'tw-top-[60px]',
        'md:tw-top-[131px]',
        'richtext-minimal'
    ]
    }
  },
  variants: {
    extend: {
      border: ["first"],
      textColor: ["group-hover"],
    },
  },
};

